services:
  db:
    image: postgres:17-alpine  # Version légère et performante de PostgreSQL
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data  # Volume persistant
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql  # Exécute le dump seulement au premier build

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres  # Connexion DB
    ports:
      - "8000:8000"
    depends_on:
      - db  # Démarre après PostgreSQL

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000  # URL de l'API pour le frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend  # Démarre après le backend

volumes:
  dbdata:  # Volume persistant pour PostgreSQL
