services:
  db:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000" 
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: react_frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:80" 
    depends_on:
      - backend

volumes:
  dbdata:
