services:
  db:
    image: postgres:17-alpine  # Version légère de PostgreSQL
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data  # Volume persistant
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql  # Exécution du dump au premier build

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000" 
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:80"  # Le container Nginx sert sur le port 80, mappé au port 3000 de l'hôte
    depends_on:
      - backend

volumes:
  dbdata:
